require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CdnaObservationsController do
  before do
    @sample = FactoryGirl.create(:sample)
  end

  # This should return the minimal set of attributes required to create a valid
  # CdnaObservation. As you add validations to CdnaObservation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      sample_id: @sample.id
    }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CdnaObservationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cdna_observations as @cdna_observations" do
      cdna_observation = CdnaObservation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cdna_observations).should eq([cdna_observation])
    end
  end

  describe "GET show" do
    it "assigns the requested cdna_observation as @cdna_observation" do
      cdna_observation = CdnaObservation.create! valid_attributes
      get :show, {:id => cdna_observation.to_param}, valid_session
      assigns(:cdna_observation).should eq(cdna_observation)
    end
  end

  describe "GET new" do
    it "assigns a new cdna_observation as @cdna_observation" do
      get :new, {}, valid_session
      assigns(:cdna_observation).should be_a_new(CdnaObservation)
    end
  end

  describe "GET edit" do
    it "assigns the requested cdna_observation as @cdna_observation" do
      cdna_observation = CdnaObservation.create! valid_attributes
      get :edit, {:id => cdna_observation.to_param}, valid_session
      assigns(:cdna_observation).should eq(cdna_observation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CdnaObservation" do
        expect {
          post :create, {:cdna_observation => valid_attributes}, valid_session
        }.to change(CdnaObservation, :count).by(1)
      end

      it "assigns a newly created cdna_observation as @cdna_observation" do
        post :create, {:cdna_observation => valid_attributes}, valid_session
        assigns(:cdna_observation).should be_a(CdnaObservation)
        assigns(:cdna_observation).should be_persisted
      end

      it "redirects to the created cdna_observation" do
        post :create, {:cdna_observation => valid_attributes}, valid_session
        response.should redirect_to(CdnaObservation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cdna_observation as @cdna_observation" do
        # Trigger the behavior that occurs when invalid params are submitted
        CdnaObservation.any_instance.stub(:save).and_return(false)
        post :create, {:cdna_observation => {}}, valid_session
        assigns(:cdna_observation).should be_a_new(CdnaObservation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CdnaObservation.any_instance.stub(:save).and_return(false)
        post :create, {:cdna_observation => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cdna_observation" do
        cdna_observation = CdnaObservation.create! valid_attributes
        # Assuming there are no other cdna_observations in the database, this
        # specifies that the CdnaObservation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CdnaObservation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cdna_observation.to_param, :cdna_observation => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cdna_observation as @cdna_observation" do
        cdna_observation = CdnaObservation.create! valid_attributes
        put :update, {:id => cdna_observation.to_param, :cdna_observation => valid_attributes}, valid_session
        assigns(:cdna_observation).should eq(cdna_observation)
      end

      it "redirects to the cdna_observation" do
        cdna_observation = CdnaObservation.create! valid_attributes
        put :update, {:id => cdna_observation.to_param, :cdna_observation => valid_attributes}, valid_session
        response.should redirect_to(cdna_observation)
      end
    end

    describe "with invalid params" do
      it "assigns the cdna_observation as @cdna_observation" do
        cdna_observation = CdnaObservation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CdnaObservation.any_instance.stub(:save).and_return(false)
        put :update, {:id => cdna_observation.to_param, :cdna_observation => {}}, valid_session
        assigns(:cdna_observation).should eq(cdna_observation)
      end

      it "re-renders the 'edit' template" do
        cdna_observation = CdnaObservation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CdnaObservation.any_instance.stub(:save).and_return(false)
        put :update, {:id => cdna_observation.to_param, :cdna_observation => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cdna_observation" do
      cdna_observation = CdnaObservation.create! valid_attributes
      expect {
        delete :destroy, {:id => cdna_observation.to_param}, valid_session
      }.to change(CdnaObservation, :count).by(-1)
    end

    it "redirects to the cdna_observations list" do
      cdna_observation = CdnaObservation.create! valid_attributes
      delete :destroy, {:id => cdna_observation.to_param}, valid_session
      response.should redirect_to(cdna_observations_url)
    end
  end

end
