require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FunctionsController do
  before do
    @annotation_source = FactoryGirl.create(:annotation_source)
  end

  # This should return the minimal set of attributes required to create a valid
  # Function. As you add validations to Function, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      name: 'Test function'
    }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FunctionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all functions as @functions" do
      function = @annotation_source.functions.create! valid_attributes
      get :index, {}, valid_session
      assigns(:functions).should eq([function])
    end
  end

  describe "GET show" do
    it "assigns the requested function as @function" do
      function = @annotation_source.functions.create! valid_attributes
      get :show, {:id => function.to_param}, valid_session
      assigns(:function).should eq(function)
    end
  end

  describe "GET new" do
    it "assigns a new function as @function" do
      get :new, {}, valid_session
      assigns(:function).should be_a_new(Function)
    end
  end

  describe "GET edit" do
    it "assigns the requested function as @function" do
      function = @annotation_source.functions.create! valid_attributes
      get :edit, {:id => function.to_param}, valid_session
      assigns(:function).should eq(function)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Function" do
        expect {
          post :create, {:function => valid_attributes.merge(annotation_source_id: @annotation_source.id)}, valid_session
        }.to change(Function, :count).by(1)
      end

      it "assigns a newly created function as @function" do
        post :create, {:function => valid_attributes.merge(annotation_source_id: @annotation_source.id)}, valid_session
        assigns(:function).should be_a(Function)
        assigns(:function).should be_persisted
      end

      it "redirects to the created function" do
        post :create, {:function => valid_attributes.merge(annotation_source_id: @annotation_source.id)}, valid_session
        response.should redirect_to(Function.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved function as @function" do
        # Trigger the behavior that occurs when invalid params are submitted
        Function.any_instance.stub(:save).and_return(false)
        post :create, {:function => {}}, valid_session
        assigns(:function).should be_a_new(Function)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Function.any_instance.stub(:save).and_return(false)
        post :create, {:function => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested function" do
        function = @annotation_source.functions.create! valid_attributes
        # Assuming there are no other functions in the database, this
        # specifies that the @annotation_source.functions.created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Function.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => function.to_param, :function => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested function as @function" do
        function = @annotation_source.functions.create! valid_attributes
        put :update, {:id => function.to_param, :function => valid_attributes}, valid_session
        assigns(:function).should eq(function)
      end

      it "redirects to the function" do
        function = @annotation_source.functions.create! valid_attributes
        put :update, {:id => function.to_param, :function => valid_attributes}, valid_session
        response.should redirect_to(function)
      end
    end

    describe "with invalid params" do
      it "assigns the function as @function" do
        function = @annotation_source.functions.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Function.any_instance.stub(:save).and_return(false)
        put :update, {:id => function.to_param, :function => {}}, valid_session
        assigns(:function).should eq(function)
      end

      it "re-renders the 'edit' template" do
        function = @annotation_source.functions.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Function.any_instance.stub(:save).and_return(false)
        put :update, {:id => function.to_param, :function => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested function" do
      function = @annotation_source.functions.create! valid_attributes
      expect {
        delete :destroy, {:id => function.to_param}, valid_session
      }.to change(Function, :count).by(-1)
    end

    it "redirects to the functions list" do
      function = @annotation_source.functions.create! valid_attributes
      delete :destroy, {:id => function.to_param}, valid_session
      response.should redirect_to(functions_url)
    end
  end

end
