require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SamplePropertiesController do

  # This should return the minimal set of attributes required to create a valid
  # SampleProperty. As you add validations to SampleProperty, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SamplePropertiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sample_properties as @sample_properties" do
      sample_property = SampleProperty.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sample_properties).should eq([sample_property])
    end
  end

  describe "GET show" do
    it "assigns the requested sample_property as @sample_property" do
      sample_property = SampleProperty.create! valid_attributes
      get :show, {:id => sample_property.to_param}, valid_session
      assigns(:sample_property).should eq(sample_property)
    end
  end

  describe "GET new" do
    it "assigns a new sample_property as @sample_property" do
      get :new, {}, valid_session
      assigns(:sample_property).should be_a_new(SampleProperty)
    end
  end

  describe "GET edit" do
    it "assigns the requested sample_property as @sample_property" do
      sample_property = SampleProperty.create! valid_attributes
      get :edit, {:id => sample_property.to_param}, valid_session
      assigns(:sample_property).should eq(sample_property)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SampleProperty" do
        expect {
          post :create, {:sample_property => valid_attributes}, valid_session
        }.to change(SampleProperty, :count).by(1)
      end

      it "assigns a newly created sample_property as @sample_property" do
        post :create, {:sample_property => valid_attributes}, valid_session
        assigns(:sample_property).should be_a(SampleProperty)
        assigns(:sample_property).should be_persisted
      end

      it "redirects to the created sample_property" do
        post :create, {:sample_property => valid_attributes}, valid_session
        response.should redirect_to(SampleProperty.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sample_property as @sample_property" do
        # Trigger the behavior that occurs when invalid params are submitted
        SampleProperty.any_instance.stub(:save).and_return(false)
        post :create, {:sample_property => {}}, valid_session
        assigns(:sample_property).should be_a_new(SampleProperty)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SampleProperty.any_instance.stub(:save).and_return(false)
        post :create, {:sample_property => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sample_property" do
        sample_property = SampleProperty.create! valid_attributes
        # Assuming there are no other sample_properties in the database, this
        # specifies that the SampleProperty created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SampleProperty.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => sample_property.to_param, :sample_property => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested sample_property as @sample_property" do
        sample_property = SampleProperty.create! valid_attributes
        put :update, {:id => sample_property.to_param, :sample_property => valid_attributes}, valid_session
        assigns(:sample_property).should eq(sample_property)
      end

      it "redirects to the sample_property" do
        sample_property = SampleProperty.create! valid_attributes
        put :update, {:id => sample_property.to_param, :sample_property => valid_attributes}, valid_session
        response.should redirect_to(sample_property)
      end
    end

    describe "with invalid params" do
      it "assigns the sample_property as @sample_property" do
        sample_property = SampleProperty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SampleProperty.any_instance.stub(:save).and_return(false)
        put :update, {:id => sample_property.to_param, :sample_property => {}}, valid_session
        assigns(:sample_property).should eq(sample_property)
      end

      it "re-renders the 'edit' template" do
        sample_property = SampleProperty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SampleProperty.any_instance.stub(:save).and_return(false)
        put :update, {:id => sample_property.to_param, :sample_property => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sample_property" do
      sample_property = SampleProperty.create! valid_attributes
      expect {
        delete :destroy, {:id => sample_property.to_param}, valid_session
      }.to change(SampleProperty, :count).by(-1)
    end

    it "redirects to the sample_properties list" do
      sample_property = SampleProperty.create! valid_attributes
      delete :destroy, {:id => sample_property.to_param}, valid_session
      response.should redirect_to(sample_properties_url)
    end
  end

end
